export declare type DeliveryRequest = {
  id: number,
  user_id: number,
  payment_request_id: number,
  status_id: number,
  pickup_address_id: number,
  delivery_address_id: number,
  pickup_time: string,
  estimated_distance: number,
  actual_distance: number,
  estimated_duration: string,
  delivery_cost: number,
  recipient_name: number,
  recipient_mobile: string,
  item_type: string,
  note: string,
  instructions: string,
  created_at: string,
  updated_at: string,
  deleted_at: number,
  status: {
    id: number,
    name: string
    color_code: string,
    description: string,
    created_at: string,
    updated_at: string,
    deleted_at: string
  },
  user: {
    id: number,
    first_name: string,
    middle_name: string,
    last_name: string,
    mobile: string,
    email: string,
    national_id_number: string,
    passport_number: string,
    is_superuser: boolean,
    role_id: number,
    referred_by: string,
    referee_id: string,
    referral_code: string,
    mobile_verified_at: string,
    email_verified_at: string,
    created_at: string,
    updated_at: string,
    corporate_name: string,
    corporate_reg_no: string,
    user_type_id: number,
    country_id: number,
    agent_type_ref: string,
    parent_ref: string,
    full_name: string,
    referrals_count: number
  },
  pickup_address: {
    id: number,
    user_id: number,
    latitude: number,
    longitude: number,
    address: string,
    detailed_address: string,
    created_at: string,
    updated_at: string,
    deleted_at: string
  },
  delivery_address: {
    id: number,
    user_id: number,
    latitude: number,
    longitude: number,
    address: string,
    detailed_address: string,
    recipient_name: string,
    recipient_mobile: string,
    created_at: string,
    updated_at: string,
    deleted_at: string
  },
  payment_request: {
    id: number,
    user_id: number,
    status_id: number,
    client_id: number,
    payment_method_id: number,
    account: string,
    amount: number,
    total_paid: number,
    balance: number,
    mobile: string,
    email: string,
    reference: string,
    TransID: string,
    MerchantRequestID: string,
    FirstName: string,
    MiddleName: string,
    LastName: string,
    TransTime: string,
    CheckoutRequestID: string,
    description: string,
    processor_response: string,
    created_at: string,
    updated_at: string,
    deleted_at: string,
    redirectUrl: string
  }
};

export declare type NewDeliveryRequest = {
  user_id: string,
  pickup_address: {
    latitude: string,
    longitude: string,
    address: string,
    detailed_address: string
  },
  delivery_address: {
    latitude: string,
    longitude: string,
    address: string,
    detailed_address: string,
  },
  recipient_name: string,
  recipient_mobile: string,
  item_type: string,
  pickup_time: string
}